# Generated by Django 5.2.1 on 2025-05-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_medium_teachingmode_subject_teacherprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='medium',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of the grade (e.g., '10th Grade', '12th Grade')", max_length=50, unique=True)),
                ('sequence', models.PositiveIntegerField(help_text="The sequence number of the grade (e.g., 10 for '10th Grade', 12 for '12th Grade')", unique=True)),
                ('medium', models.ManyToManyField(blank=True, related_name='subjects', to='base.medium')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='The grade level for which this subject is applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='base.grade'),
        ),
    ]
