# Generated by Django 5.2.1 on 2025-05-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_subject_medium_grade_alter_subject_grade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['tutor__user__username', 'day_of_week', 'start_time'], 'verbose_name': 'Availability Slot', 'verbose_name_plural': 'Availability Slots'},
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacher',
            new_name='user',
        ),
    ]
