# Generated by Django 5.2.1 on 2025-06-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, help_text="Comma separated values: lat,lon,accuracy (e.g., '23.4567,90.1234,10')", max_length=100, null=True),
        ),
    ]
