# Generated by Django 5.2.1 on 2025-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='verified',
            field=models.BooleanField(default=False, help_text="Indicates if the teacher's profile has been verified by an admin."),
        ),
    ]
